spring.application.name=chat-server-v3
server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

chat.exchange.name=chat.exchange
chat.queue.prefix=room.

spring.datasource.url=jdbc:postgresql://localhost:5432/cs6650_chat
spring.datasource.username=maisuiyang
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

resilience4j.ratelimiter.instances.metricsApi.limit-for-period=60
resilience4j.ratelimiter.instances.metricsApi.limit-refresh-period=1s
resilience4j.ratelimiter.instances.metricsApi.timeout-duration=0
